// Generated by CoffeeScript 2.7.0
(function() {
  var base, cmd, epis, exec, file, fs, i, key, len, matches, nfo, nfoFiles, parts, ref, seasonPath;

  fs = require('fs-plus');

  exec = require('child_process').execSync;

  // console.log ".... pruning local duplicate episode files ...."
  epis = {};

  nfoFiles = exec("find /mnt/media/tv -name '*.nfo'");

  ref = nfoFiles.toString().split('\n');
  for (i = 0, len = ref.length; i < len; i++) {
    file = ref[i];
    if (!(file && file.indexOf('/season.nfo') === -1)) {
      continue;
    }
    // if file.indexOf('Worst') == -1 then continue
    parts = file.split('/');
    parts.pop();
    seasonPath = parts.join('/');
    nfo = fs.readFileSync(file, 'utf8');
    matches = /<episode>(\d+)<\/episode>/i.exec(nfo);
    if (!matches) {
      // console.log '>>>>> no episode match', file
      continue;
    }
    key = seasonPath + '~' + matches[1];
    if (epis[key]) {
      parts = file.split('.');
      parts.pop();
      base = parts.join('.');
      cmd = 'rm "' + base + '"*';
      console.log('deleting local duplicate file:\n    ', key, '\n    ', cmd);
      exec(cmd);
    }
    epis[key] = true;
  }

}).call(this);
