#! /bin/bash

s="$(pgrep -f tv-proc/main.js)"
if [ ${#s} -gt 1 ] ; then
  echo "stopping, tv-proc already running"
  exit
fi
cd /root/dev/apps/tv-proc
echo >> /root/dev/apps/tv-proc/tv.log
date >> /root/dev/apps/tv-proc/tv.log
/root/.nvm/versions/node/v16.15.1/bin/node /root/dev/apps/tv-proc/main.js $1 \
    >> /root/dev/apps/tv-proc/tv.log 
chmod -R 774  /mnt/media/tv
chown -R emby /mnt/media/tv
/root/.nvm/versions/node/v16.15.1/bin/node /root/dev/apps/tv-proc/prune-dupes.js\
    >> /root/dev/apps/tv-proc/tv.log
date >> /root/dev/apps/tv-proc/tv.log
chmod -R 774  /mnt/media/tv
chown -R emby /mnt/media/tv
