#! /bin/bash

echo >> /root/dev/apps/tv-proc/tv.log
date >> /root/dev/apps/tv-proc/tv.log

s="$(pgrep -f tv-proc/main.js)"
if [ ${#s} -gt 1 ] ; then
  echo "--  tv-proc not started, main.js already running  --"
  echo >> /root/dev/apps/tv-proc/tv.log
  exit
fi
s="$(pgrep -f tv-proc/movie.js)"
if [ ${#s} -gt 1 ] ; then
  echo "--  tv-proc not started, movie.js already running  --"
  echo >> /root/dev/apps/tv-proc/tv.log
  exit
fi

cd /root/dev/apps/tv-proc
/root/.nvm/versions/node/v16.15.1/bin/node /root/dev/apps/tv-proc/main.js $1 \
    >> /root/dev/apps/tv-proc/tv.log 

chmod -R 774  /mnt/media/tv
chown -R emby /mnt/media/tv

/root/.nvm/versions/node/v16.15.1/bin/node /root/dev/apps/tv-proc/prune-dupes.js \
    >> /root/dev/apps/tv-proc/tv.log
# date >> /root/dev/apps/tv-proc/tv.log
chmod -R 774  /mnt/media/tv
chown -R emby /mnt/media/tv
